options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: Install dependencies
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: Build React App
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'test-reactjs',
        '--source', '.',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]
