options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
#  - name: 'gcr.io/cloud-builders/npm'
#    id: Install dependencies
#    args: ['install']
#
#  - name: 'gcr.io/cloud-builders/npm'
#    id: Build React App
#    args: ['run', 'build']
#
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    id: Deploy to Cloud Run
#    entrypoint: 'gcloud'
#    args:
#      [
#        'run', 'deploy', 'test-reactjs',
#        '--source', '.',
#        '--region', 'us-central1',
#        '--allow-unauthenticated',
#      ]
  # Step 1: Build Docker image (only locally in Cloud Build VM)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-react-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: List Image
    args: ['images']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/simple-react-app']

  # Step 2: Deploy to Cloud Run using local image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker -q
        
        gcloud run deploy simple-react-app \
          --image gcr.io/$PROJECT_ID/simple-react-app \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
